name = "anabelian"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Anabelian"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "065356127b1dc0016f66b7283ce0ce2c4055aa55"

[[lean_lib]]
name = "Anabelian"

[[require]]
name = "ClassFieldTheory"
git = "https://github.com/n-yamaguchi-0729/ClassFieldTheory"
rev = "7713795234690681b4406ae198b07aa95e82716a"
