/-
Copyright (c) 2026 Conor Mahany. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Conor Mahany
-/
import Anabelian.ExtensionMonogenic

/-!
# The descent, rung 4 (second half): the monogenicity engine (Pass 32)

**The `hgen` half of the monogenicity package** — Serre's digit-expansion argument
(*Local Fields*, I §6, Prop. 18's skeleton), Nakayama-finished: under **totally-ramified data**

* `hres` — residues are covered by the base (`∀ x, ∃ a, x − ι a ∈ 𝔪_L`: trivial residue
  extension), and
* `he` — some power of `𝔪_L` falls into the base's maximal ideal (`𝔪_L^e ≤ (ι 𝔪[K])·𝒪_L`),

the subring generated by the base image and a uniformizer is **everything**:

> `Subring.closure (range(𝒪[K] → 𝒪_L) ∪ {π}) = ⊤`.

The proof: a finite π-adic digit expansion (`∀ n x, ∃ s ∈ S, x − s ∈ 𝔪_L^n`, induction via
`hres`), run to depth `e` so the error lands in `𝔪[K]·𝒪_L`; then `S ⊔ 𝔪[K]·⊤ = ⊤` and
**Nakayama** (`𝒪_L` is module-finite over the local `𝒪[K]`, Pass 29/32) closes `S = ⊤`. No
completeness needed — module-finiteness replaces it.

With `smul_extensionAlgebraMap_range_eq` (the free `hfix` half), this is the **full
monogenicity package of Passes 25/27/28, discharged for totally-ramified data** — the two
hypotheses `hres`/`he` are exactly "L/K is totally ramified", to be supplied by the
`e·f = n` bookkeeping (the block's next rung) or by hand in concrete cases.

## Honesty

This is the totally-ramified case: `hres` and `he` are honest *named data* (not silently
assumed), and the general case (`A₀ = 𝒪_{L₀}`, the maximal unramified subextension) is named
future work — the classical reduction runs through exactly this engine over `L₀`. No new
`structure`/`class`; no owed witness (the hypotheses are used constructively; no
irremovability claimed); D1 N/A; D2 N/A. Recovers nothing from an abstract group; R1–R3
untouched.

## Axiom status

Standard axioms only (`#print axioms` below). Ledger: `0 FOUNDATIONAL / 0 DEBT`, unchanged.
-/

namespace Anabelian

open scoped ValuativeRel
open ValuativeRel IsLocalRing

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
variable (L : Type*) [Field L] [Algebra K L] [FiniteDimensional K L]

/-- **The monogenicity engine** (totally-ramified case; Serre I §6 Prop. 18's skeleton,
Nakayama-finished): if residues are covered by the base (`hres`) and some `𝔪_L`-power falls
into `(ι 𝔪[K])·𝒪_L` (`he`), then `𝒪_L` is generated as a ring by the base image together with
the uniformizer. This is the `hgen` half of the Passes-25/27/28 monogenicity package. -/
theorem closure_range_union_uniformizer_eq_top [Algebra.IsSeparable K L]
    (π : ↥(extensionIntegers K L))
    (hspan : maximalIdeal ↥(extensionIntegers K L) = Ideal.span {π})
    (hres : ∀ x : ↥(extensionIntegers K L), ∃ a : ↥𝒪[K],
      x - extensionAlgebraMap K L a ∈ maximalIdeal ↥(extensionIntegers K L))
    (e : ℕ) (he : (maximalIdeal ↥(extensionIntegers K L)) ^ e ≤
      Ideal.map (extensionAlgebraMap K L) (maximalIdeal ↥𝒪[K])) :
    Subring.closure
      (((extensionAlgebraMap K L).range : Set ↥(extensionIntegers K L)) ∪ {π}) = ⊤ := by
  set S := Subring.closure
    (((extensionAlgebraMap K L).range : Set ↥(extensionIntegers K L)) ∪ {π}) with hS
  have hπS : π ∈ S := Subring.subset_closure (Or.inr rfl)
  have hιS : ∀ a : ↥𝒪[K], extensionAlgebraMap K L a ∈ S :=
    fun a => Subring.subset_closure (Or.inl ⟨a, rfl⟩)
  have hπm : π ∈ maximalIdeal ↥(extensionIntegers K L) := by
    rw [hspan]; exact Ideal.mem_span_singleton_self π
  -- S as an 𝒪[K]-submodule
  let N : Submodule ↥𝒪[K] ↥(extensionIntegers K L) :=
    { carrier := S
      add_mem' := fun ha hb => S.add_mem ha hb
      zero_mem' := S.zero_mem
      smul_mem' := fun c x hx => by
        have h1 : c • x = extensionAlgebraMap K L c * x := by
          rw [Algebra.smul_def]; rfl
        rw [SetLike.mem_coe, h1]
        exact S.mul_mem (hιS c) hx }
  -- the digit expansion
  have claim : ∀ n : ℕ, ∀ x : ↥(extensionIntegers K L),
      ∃ s ∈ S, x - s ∈ (maximalIdeal ↥(extensionIntegers K L)) ^ n := by
    intro n
    induction n with
    | zero =>
      intro x
      refine ⟨0, S.zero_mem, ?_⟩
      rw [pow_zero, Ideal.one_eq_top]
      exact Submodule.mem_top
    | succ n ih =>
      intro x
      obtain ⟨a, ha⟩ := hres x
      rw [hspan, Ideal.mem_span_singleton] at ha
      obtain ⟨y, hy⟩ := ha
      obtain ⟨s, hsS, hs⟩ := ih y
      refine ⟨extensionAlgebraMap K L a + π * s,
        S.add_mem (hιS a) (S.mul_mem hπS hsS), ?_⟩
      have h2 : x - (extensionAlgebraMap K L a + π * s) = (y - s) * π := by
        linear_combination hy
      rw [h2, pow_succ]
      exact Ideal.mul_mem_mul hs hπm
  -- elements of (ι 𝔪[K])·𝒪_L lie in 𝔪[K] • ⊤
  have hbridge : ∀ z, z ∈ Ideal.map (extensionAlgebraMap K L) (maximalIdeal ↥𝒪[K]) →
      z ∈ (maximalIdeal ↥𝒪[K]) • (⊤ : Submodule ↥𝒪[K] ↥(extensionIntegers K L)) := by
    intro z hz
    have hz' : z ∈ Ideal.span ((extensionAlgebraMap K L : ↥𝒪[K] → ↥(extensionIntegers K L)) ''
        (maximalIdeal ↥𝒪[K])) := hz
    clear hz
    induction hz' using Submodule.span_induction with
    | mem w hw =>
      obtain ⟨m, hm, rfl⟩ := hw
      have h3 : extensionAlgebraMap K L m = m • (1 : ↥(extensionIntegers K L)) := by
        rw [Algebra.smul_def, mul_one]; rfl
      rw [h3]
      exact Submodule.smul_mem_smul hm Submodule.mem_top
    | zero => exact Submodule.zero_mem _
    | add a b _ _ iha ihb => exact Submodule.add_mem _ iha ihb
    | smul r w _ ihw =>
      rw [smul_eq_mul]
      refine Submodule.smul_induction_on ihw ?_ ?_
      · intro m hm n _
        have h4 : r * (m • n) = m • (r * n) := mul_smul_comm m r n
        rw [h4]
        exact Submodule.smul_mem_smul hm Submodule.mem_top
      · intro a b ha hb
        rw [mul_add]
        exact Submodule.add_mem _ ha hb
  -- Nakayama: ⊤ ≤ N ⊔ 𝔪[K] • ⊤, so ⊤ ≤ N
  have htop : (⊤ : Submodule ↥𝒪[K] ↥(extensionIntegers K L)) ≤
      N ⊔ (maximalIdeal ↥𝒪[K]) • ⊤ := by
    intro x _
    obtain ⟨s, hsS, hsm⟩ := claim e x
    have h5 : x = s + (x - s) := by ring
    rw [h5]
    exact Submodule.add_mem _ (Submodule.mem_sup_left hsS)
      (Submodule.mem_sup_right (hbridge _ (he hsm)))
  have hNak : (⊤ : Submodule ↥𝒪[K] ↥(extensionIntegers K L)) ≤ N :=
    Submodule.le_of_le_smul_of_le_jacobson_bot (Module.finite_def.mp inferInstance)
      (IsLocalRing.maximalIdeal_le_jacobson ⊥) htop
  refine (Subring.eq_top_iff' S).mpr (fun x => ?_)
  exact hNak Submodule.mem_top

-- Reproducible axiom audit (re-runs on every `lake build`). All standard-axioms-only.
#print axioms closure_range_union_uniformizer_eq_top

end Anabelian
