/-
Copyright (c) 2026 Conor Mahany. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Conor Mahany
-/
import Anabelian.ExtensionMonogenicTop

/-!
# The descent, rung 5 (first half): the engine's data, discharged (Pass 33)

The Pass-32 engine consumed two named inputs. This file discharges them from honest data:

* **`exists_pow_maximalIdeal_le_map`** — the `he` input holds **unconditionally** for every
  finite separable `L/K`: in the DVR `𝒪_L`, the ideal generated by `ι ϖ_K` is automatically a
  power of `𝔪_L` (the DVR ideal classification) — no totally-ramified assumption needed. The
  exponent is the ramification index `e`, though no numerical bookkeeping is required here.
* **`residue_sub_mem_of_surjective`** — the `hres` input reduces to **surjectivity of the
  residue extension** `𝓀[K] → 𝓀_L` (i.e. `f = 1`, the honest meaning of "totally ramified").

So of the engine's two hypotheses, one was never a hypothesis at all, and the other is exactly
the residue-triviality datum. The assembly (the `hgen` package + the instantiated tame
injectivity) is `Anabelian/ExtensionTotallyRamified.lean`.

## Honesty

No new hypotheses introduced; one discharged outright, one reduced to its honest form. No new
`structure`/`class`; no owed witness; D1 N/A; D2 N/A. Recovers nothing from an abstract group;
R1–R3 untouched.

## Axiom status

Standard axioms only (`#print axioms` below). Ledger: `0 FOUNDATIONAL / 0 DEBT`, unchanged.
-/

namespace Anabelian

open scoped ValuativeRel
open ValuativeRel IsLocalRing

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
variable (L : Type*) [Field L] [Algebra K L] [FiniteDimensional K L]

/-- **The `he` input of the Pass-32 engine holds unconditionally**: some power of `𝔪_L` lies in
`(ι 𝔪[K])·𝒪_L`. In the DVR `𝒪_L`, the nonzero non-unit `ι ϖ_K` factors as `unit · π_L^e`, so
`𝔪_L^e = (ι ϖ_K) ≤ Ideal.map ι 𝔪[K]`. (The exponent is the ramification index.) -/
theorem exists_pow_maximalIdeal_le_map [Algebra.IsSeparable K L] :
    ∃ e : ℕ, (maximalIdeal ↥(extensionIntegers K L)) ^ e ≤
      Ideal.map (extensionAlgebraMap K L) (maximalIdeal ↥𝒪[K]) := by
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible ↥𝒪[K]
  obtain ⟨πL, hπL⟩ := IsDiscreteValuationRing.exists_irreducible ↥(extensionIntegers K L)
  have hx0 : extensionAlgebraMap K L ϖ ≠ 0 := by
    intro h
    have h1 := congrArg Subtype.val h
    rw [coe_extensionAlgebraMap] at h1
    exact hϖ.ne_zero (Subtype.ext ((map_eq_zero (algebraMap K L)).mp h1))
  obtain ⟨n, u, hu⟩ :=
    IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hx0 hπL
  refine ⟨n, ?_⟩
  have hspanL : maximalIdeal ↥(extensionIntegers K L) = Ideal.span {πL} :=
    (IsDiscreteValuationRing.irreducible_iff_uniformizer πL).mp hπL
  have h2 : (maximalIdeal ↥(extensionIntegers K L)) ^ n
      = Ideal.span {extensionAlgebraMap K L ϖ} := by
    rw [hspanL, Ideal.span_singleton_pow]
    refine (Ideal.span_singleton_eq_span_singleton.mpr ?_).symm
    refine ⟨u⁻¹, ?_⟩
    rw [hu]
    calc (↑u * πL ^ n) * (↑u⁻¹ : ↥(extensionIntegers K L))
        = πL ^ n * (↑u * ↑u⁻¹) := by ring
      _ = πL ^ n := by rw [Units.mul_inv, mul_one]
  rw [h2, Ideal.span_singleton_le_iff_mem]
  exact Ideal.mem_map_of_mem _ ((IsLocalRing.mem_maximalIdeal _).mpr hϖ.not_isUnit)

/-- **The `hres` input of the Pass-32 engine, from residue surjectivity**: if the residue
extension `𝓀[K] → 𝓀_L` is surjective (`f = 1` — the honest "totally ramified" datum), then
every element of `𝒪_L` is congruent mod `𝔪_L` to a base element. -/
theorem residue_sub_mem_of_surjective
    (hsurj : Function.Surjective (ResidueField.map (extensionAlgebraMap K L)))
    (x : ↥(extensionIntegers K L)) :
    ∃ a : ↥𝒪[K], x - extensionAlgebraMap K L a ∈ maximalIdeal ↥(extensionIntegers K L) := by
  obtain ⟨ā, hā⟩ := hsurj (residue _ x)
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective ā
  refine ⟨a, ?_⟩
  have h1 : residue ↥(extensionIntegers K L) (extensionAlgebraMap K L a)
      = residue ↥(extensionIntegers K L) x := by
    rw [← ResidueField.map_residue]
    exact hā
  exact (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).mp h1.symm

-- Reproducible axiom audit (re-runs on every `lake build`). All standard-axioms-only.
#print axioms exists_pow_maximalIdeal_le_map
#print axioms residue_sub_mem_of_surjective

end Anabelian
