/-
Copyright (c) 2026 Conor Mahany. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Conor Mahany
-/
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.FieldTheory.Galois.GaloisClosure
import Mathlib.FieldTheory.Galois.Infinite

/-!
# Rung L1: structure of the absolute Galois group of a finite field

Axiom-free, genuinely Galois-theoretic lemmas on rung **L1** (Galois theory of local/finite fields)
of `ROADMAP.md`: **commutativity** (Pass 1) and **procyclicity / topological generation by
Frobenius** (Pass 2). Together these say `Gal(𝔽_q̄/𝔽_q)` is an abelian group topologically generated
by one element — the abstract-group skeleton of `Ẑ` (full `≅ Ẑ` remains an L1 sub-target).

## What is proved

`Anabelian.absoluteGaloisGroup_mul_comm`: for a finite field `F`, the absolute Galois group
`Gal(F̄/F) = AlgebraicClosure F ≃ₐ[F] AlgebraicClosure F` is **commutative**. (This type is
`Field.absoluteGaloisGroup F` by definition; the named-object form is recorded as the instance
`Anabelian.finiteField_absoluteGaloisGroup_isMulCommutative`.)

Mathematically this is the statement that `Gal(𝔽_q̄/𝔽_q)` is abelian — indeed it is the procyclic
group `Ẑ`, the profinite completion of `ℤ`, topologically generated by the Frobenius `x ↦ x^q`.
We prove only commutativity here; the identification with `Ẑ` is a further L1 sub-target
(`ROADMAP.md`).

## Why this is genuine L1 content (not a Pass-0 restatement, not a smoke test)

Pass 0 proved a property of *every* Galois extension via the abstract correspondence; it said
nothing about *which* group occurs. This lemma is a *specific structural fact about a specific
absolute Galois group*, and it is **special to finite (and, downstream, unramified-local) fields**:
the absolute Galois group of a general field is highly non-commutative (e.g. `Gal(ℚ̄/ℚ)`). It is not
in Mathlib (searched: no commutativity / abelian / procyclic statement for finite-field Galois
groups), and the proof exercises finite-field-specific API that Pass 0 never touched — the Frobenius
generation of finite Galois groups (`IsCyclic Gal(L/K)` for finite `L`) plus reduction to finite
subextensions.

The commutativity of `Gal(𝔽_q̄/𝔽_q)` is the prototype of the abelian Galois structure that local
class field theory (L3) and local reconstruction (R1) exploit: the unramified quotient of a
local-field Galois group *is* `Gal(𝔽_q̄/𝔽_q)`.

## The load-bearing hypothesis

`[Finite F]` is essential, used twice: (i) `Module.finite_of_finite` makes each finite-dimensional
subextension a *finite field*; (ii) over a finite field every finite Galois group is *cyclic*
(`IsCyclic Gal(L/K)`, generated by Frobenius), hence commutative. Drop finiteness and the
conclusion is false: `Gal(ℚ̄/ℚ)` is non-abelian, witnessed by the non-normal subextension
`ℚ(∛2)/ℚ` (an abelian group has all subgroups normal, which via `normal_iff_isGalois` would force
every subextension to be Galois — but `ℚ(∛2)/ℚ` is not). That come-apart witness is not formalized
in this pass (it is a separate, non-trivial construction); it is flagged in `NOTES.md` as a future
micro-target. No `structure`/`class` is introduced here, so the rule-2 obligation does not bind.

## What this is NOT

Not reconstruction. The statement is about the action of `Gal(F̄/F)` on the *given* field `F̄`; it
recovers nothing from an abstract topological group. The hard converse direction (R1–R3) is
untouched.

## Axiom status

Standard axioms only (`propext`, `Classical.choice`, `Quot.sound`), verified by the in-file
`#print axioms` below. Pass-1 ledger delta: **0 / 0** (`AXIOM_LEDGER.md`).

## Main Mathlib API doing the real work

* `FiniteField`'s instance `IsCyclic Gal(L/K)` for finite `L` (Frobenius generates), hence
  `IsCyclic.isMulCommutative`.
* `FiniteGaloisIntermediateField.adjoin` / `subset_adjoin` — a finite Galois subextension
  containing a chosen point.
* `AlgEquiv.restrictNormalHom` (a `MonoidHom`) and `AlgEquiv.restrictNormalHom_apply`.
* `Module.finite_of_finite` — a finite-dimensional space over a finite ring is finite.
-/

open scoped IntermediateField

namespace Anabelian

/-- **The absolute Galois group of a finite field is commutative.**
For a finite field `F`, any two `F`-automorphisms of `AlgebraicClosure F` commute. The carrier
`Gal(AlgebraicClosure F / F)` is `Field.absoluteGaloisGroup F` by definition.

Proof idea: each `x : F̄` lies in a finite Galois subextension `M` (a finite field), on which the
Galois group is cyclic (generated by Frobenius) hence commutative; restricting `σ, τ` to `M`,
their restrictions commute, and `σ τ` and `τ σ` therefore agree on `x`. -/
theorem absoluteGaloisGroup_mul_comm (F : Type*) [Field F] [Finite F]
    (σ τ : Gal(AlgebraicClosure F/F)) : σ * τ = τ * σ := by
  apply AlgEquiv.ext
  intro x
  -- `M`: a finite Galois subextension of `F̄/F` containing `x`.
  set M := FiniteGaloisIntermediateField.adjoin F ({x} : Set (AlgebraicClosure F))
  have hx : x ∈ M.1 := FiniteGaloisIntermediateField.subset_adjoin F {x} rfl
  -- `M` is finite-dimensional over the finite field `F`, hence a finite field, hence `Gal(M/F)`
  -- is cyclic (Frobenius-generated) and therefore commutative.
  haveI : Finite M.1 := Module.finite_of_finite F
  have key : (AlgEquiv.restrictNormalHom M.1) (σ * τ)
           = (AlgEquiv.restrictNormalHom M.1) (τ * σ) := by
    rw [map_mul, map_mul, mul_comm']
  -- transport the commuting restrictions back to the point `x`.
  have e1 := AlgEquiv.restrictNormalHom_apply M.1 (σ * τ) ⟨x, hx⟩
  have e2 := AlgEquiv.restrictNormalHom_apply M.1 (τ * σ) ⟨x, hx⟩
  rw [key] at e1
  exact e1.symm.trans e2

/-- The commutativity of `Field.absoluteGaloisGroup F` for a finite field `F`, as a reusable mixin
instance (the form downstream code consumes). -/
instance finiteField_absoluteGaloisGroup_isMulCommutative
    (F : Type*) [Field F] [Finite F] : IsMulCommutative (Field.absoluteGaloisGroup F) :=
  ⟨⟨absoluteGaloisGroup_mul_comm F⟩⟩

-- Reproducible axiom audit (re-runs on every `lake build`). Expected: the three standard axioms.
#print axioms absoluteGaloisGroup_mul_comm
#print axioms finiteField_absoluteGaloisGroup_isMulCommutative

/-!
## Procyclicity: Frobenius topologically generates `Gal(𝔽_q̄/𝔽_q)` (Pass 2)

The carrier `Gal(AlgebraicClosure K/K)` is `Field.absoluteGaloisGroup K` by definition;
`frobeniusAlgEquivOfAlgebraic K (AlgebraicClosure K)` is the **Frobenius element** `x ↦ x^q`
(`q = #K`) of that group.

**Genuine L1 content, not a restatement.** Pass 1 proved `Gal(𝔽_q̄/𝔽_q)` is abelian; this proves the
strictly stronger structural fact that it is **procyclic** — topologically generated by the single
element Frobenius. It is special to finite fields (`Gal(ℚ̄/ℚ)` is not even abelian) and is the
abstract-group skeleton of the isomorphism `Gal(𝔽_q̄/𝔽_q) ≅ Ẑ` (which needs the `Ẑ` identification;
logged as a remaining L1 sub-target in `ROADMAP.md`). It uses the finite-field Frobenius API
(`coe_frobeniusAlgEquivOfAlgebraic`, `bijective_frobeniusAlgEquivOfAlgebraic_pow`) and the infinite
Galois correspondence — content Pass 1 did not touch.

**Not reconstruction.** The statements are about the action of the given Frobenius on the given
`𝔽_q̄`; nothing is recovered from an abstract topological group.

**Load-bearing hypothesis.** `[Fintype K]` (finiteness of the base) is load-bearing — procyclicity,
like commutativity, fails for infinite fields. The come-apart witness (`Gal(ℚ̄/ℚ)` non-abelian,
hence non-procyclic) is the *same* obligation Pass 1 owed, tracked as **W1** in `AXIOM_LEDGER.md`'s
"Owed
witnesses" section (not formalized here; Mathlib lacks the non-normal-extension API). Per the
extended rule-2 (`CLAUDE.md`), this is a registered, tracked obligation — not a prose aside.

**Axioms.** Standard only (in-file `#print axioms` below). Ledger delta this pass: **0 / 0**.
-/

open FiniteField

/-- **Frobenius's fixed field is the base field.** For a finite field `K`, the only elements of
`AlgebraicClosure K` fixed by every power of the Frobenius `x ↦ x^q` are those of `K` (i.e. `⊥`).
This is the generation core of procyclicity: by the infinite Galois correspondence it is equivalent
to Frobenius topologically generating the absolute Galois group
(`frobenius_topologicalClosure_eq_top`). -/
theorem frobenius_zpowers_fixedField (K : Type*) [Field K] [Fintype K] :
    IntermediateField.fixedField
        (Subgroup.zpowers (frobeniusAlgEquivOfAlgebraic K (AlgebraicClosure K))) = ⊥ := by
  apply le_antisymm _ bot_le
  intro x hx
  rw [IntermediateField.mem_fixedField_iff] at hx
  -- `x` is fixed by Frobenius, i.e. `x ^ q = x`, hence by every `q`-power iterate.
  have hφx : (frobeniusAlgEquivOfAlgebraic K (AlgebraicClosure K)) x = x :=
    hx _ (Subgroup.mem_zpowers _)
  have hxq : x ^ (Fintype.card K) = x := by
    have h := hφx; rw [coe_frobeniusAlgEquivOfAlgebraic] at h; simpa using h
  have pow_iter : ∀ j : ℕ, x ^ (Fintype.card K ^ j) = x := by
    intro j
    induction j with
    | zero => simp
    | succ n ih => rw [pow_succ, pow_mul, ih]; exact hxq
  -- It suffices to show `x` is fixed by *every* automorphism (`x ∈ ⊥`).
  rw [InfiniteGalois.mem_bot_iff_fixed]
  intro g
  -- On the finite Galois subextension generated by `x`, every automorphism is a Frobenius power.
  set M := FiniteGaloisIntermediateField.adjoin K ({x} : Set (AlgebraicClosure K)) with hM
  have hxM : x ∈ M.1 := FiniteGaloisIntermediateField.subset_adjoin K {x} rfl
  haveI : Finite M.1 := Module.finite_of_finite K
  have hpow : ∀ (n : ℕ) (y : M.1),
      (frobeniusAlgEquivOfAlgebraic K M.1 ^ n) y = y ^ (Fintype.card K ^ n) := by
    intro n
    induction n with
    | zero => intro y; simp
    | succ m ih =>
        intro y
        rw [pow_succ, AlgEquiv.mul_apply]
        simp only [coe_frobeniusAlgEquivOfAlgebraic]
        rw [ih, ← pow_mul, ← pow_succ']
  obtain ⟨j, hj⟩ := (bijective_frobeniusAlgEquivOfAlgebraic_pow K M.1).surjective
    (AlgEquiv.restrictNormalHom M.1 g)
  have e := AlgEquiv.restrictNormalHom_apply M.1 g ⟨x, hxM⟩
  rw [← hj, hpow] at e
  rw [SubmonoidClass.coe_pow] at e
  have hgx : g x = x ^ (Fintype.card K ^ j.1) := by simpa using e.symm
  rw [hgx]; exact pow_iter j.1

/-- **Procyclicity: Frobenius topologically generates the absolute Galois group of a finite field.**
The topological closure of the subgroup generated by the Frobenius `x ↦ x^q` is the whole group
`Gal(𝔽_q̄/𝔽_q)`. (Equivalently, `Gal(𝔽_q̄/𝔽_q)` is procyclic.) -/
theorem frobenius_topologicalClosure_eq_top (K : Type*) [Field K] [Fintype K] :
    (Subgroup.zpowers (frobeniusAlgEquivOfAlgebraic K (AlgebraicClosure K))).topologicalClosure
      = ⊤ := by
  -- The closure has the same (trivial) fixed field as `zpowers Frobenius`, since it is larger.
  have hfix : IntermediateField.fixedField
      (⟨(Subgroup.zpowers (frobeniusAlgEquivOfAlgebraic K (AlgebraicClosure K))).topologicalClosure,
        (Subgroup.zpowers _).isClosed_topologicalClosure⟩ :
          ClosedSubgroup Gal(AlgebraicClosure K/K)).toSubgroup = ⊥ := by
    apply le_antisymm _ bot_le
    intro y hy
    rw [IntermediateField.mem_fixedField_iff] at hy
    have : y ∈ IntermediateField.fixedField
        (Subgroup.zpowers (frobeniusAlgEquivOfAlgebraic K (AlgebraicClosure K))) := by
      rw [IntermediateField.mem_fixedField_iff]
      exact fun f hf => hy f (Subgroup.le_topologicalClosure _ hf)
    rwa [frobenius_zpowers_fixedField] at this
  -- A closed subgroup with fixed field `⊥` is the whole group (Galois correspondence).
  have h := InfiniteGalois.fixingSubgroup_fixedField
    (⟨(Subgroup.zpowers (frobeniusAlgEquivOfAlgebraic K (AlgebraicClosure K))).topologicalClosure,
      (Subgroup.zpowers _).isClosed_topologicalClosure⟩ : ClosedSubgroup Gal(AlgebraicClosure K/K))
  rw [hfix, IntermediateField.fixingSubgroup_bot] at h
  exact h.symm

#print axioms frobenius_zpowers_fixedField
#print axioms frobenius_topologicalClosure_eq_top

end Anabelian
