/-
Copyright (c) 2026 Conor Mahany. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Conor Mahany
-/
import Anabelian.TameCharacter
import Mathlib.RingTheory.IntegralDomain

/-!
# Rung L2: tame injectivity `G₀/G₁ ↪ 𝓀ˣ` under an explicit monogenicity hypothesis (Pass 25)

Pass 24 built the tame character `θ₀ : G₀ →* 𝓀ˣ` with `G₁ ≤ ker θ₀` and deliberately did **not**
claim injectivity: classically, `ker θ₀ = G₁` needs `σ ∈ G_i` to be *detectable on the single
element `π`* (`σπ − π ∈ 𝔪^(i+1) ⟹ σ ∈ G_i`), which holds when the valuation ring is **monogenic**
over an inertia-fixed subring (Serre, *Local Fields*, IV §1 Prop. 5) — genuinely absent at the bare
`ValuationSubring` abstraction level, and absent from Mathlib as a general theorem (re-verified
this pass: only `PowerBasis.adjoin_gen_eq_top`-style machinery exists; no
complete-DVR-extension monogenicity).

This file therefore takes monogenicity as an **explicit hypothesis** — the same
hypothesis-parametrized shape as Pass 23's Krull separation hypothesis — and proves the full
level-0 quotient structure from it:

* `Anabelian.smul_sub_dvd_of_mem_closure` — the engine: if `σ` fixes `A₀` pointwise and
  `x ∈ Subring.closure (A₀ ∪ {π})`, then `(σπ − π) ∣ (σx − x)`. By `Subring.closure_induction`
  (the induction *is* Serre's telescoping; the `mul` case is
  `σ(xy) − xy = σx·(σy − y) + (σx − x)·y`).
* `Anabelian.mem_ramificationGroup_of_smul_uniformizer_sub_mem` — **detection on `π`**
  (Serre IV §1 Prop. 5, monogenic form): under generation `closure (A₀ ∪ {π}) = ⊤` and
  `σ`-fixedness of `A₀`, `σπ − π ∈ 𝔪^(i+1) ⟹ σ ∈ G_i`.
* `Anabelian.ker_tameCharacter` — **`ker θ₀ = G₁`** (as `(G₁).subgroupOf G₀`): `⊇` is Pass 24's
  `tameCharacter_eq_one`; `⊆` reads `θ₀(σ) = 1` as `u_σ ≡ 1 mod 𝔪`, whence
  `σπ − π = π(u_σ − 1) ∈ 𝔪²`, and detection at `i = 1` finishes.
* `Anabelian.tameQuotientHom_injective` — **`G₀/G₁ ↪ 𝓀ˣ`**: the Pass-24 `tameQuotientHom` is
  injective (`QuotientGroup.ker_lift` + the kernel identification + `map_mk'_self`).
* `Anabelian.tameQuotient_mul_comm` — corollary: **`G₀/G₁` is commutative** (it injects into the
  abelian `𝓀ˣ`).
* `Anabelian.tameQuotient_isCyclic` — corollary: for finite `G₀`, **`G₀/G₁` is cyclic**
  (`isCyclic_of_injective_ringHom` applied to `Units.coeHom ∘ θ̄₀` into the residue field —
  a finite group embedding in the units of a domain is cyclic).

Together with Pass 24 this completes Serre IV §2 Prop. 7 at level 0, *conditionally on
monogenicity* — the textbook tame quotient structure.

## Honesty: the hypothesis, and what is NOT claimed

* The monogenicity hypothesis (`hgen : Subring.closure (↑A₀ ∪ {π}) = ⊤` with `A₀` fixed
  elementwise by the relevant `σ`) is **not claimed irremovable** from any conclusion here — no
  constructed counterexample (a non-monogenic `A` with `ker θ₀ ≠ G₁`) is attempted, so per the
  extended rule-2 no load-bearing claim is made and no owed witness is incurred (Pass 23's Krull
  precedent). It is a *sufficient* input, used constructively.
* **Discharging the hypothesis** — producing `(A₀, π)` with these properties for `A = 𝒪_L`,
  `L/K` finite, from completeness/Eisenstein (Serre IV §1 Prop. 5's own proof) — is the named
  follow-on work, blocked on the (verified absent) finite-extension
  `IsNonarchimedeanLocalField` instances (`ROADMAP.md`, L2 prerequisite gaps).
* The additive analogues at `i ≥ 1` (`G_i/G_{i+1} ↪ 𝓀⁺`) are **not** attempted here (named L2
  work, same engine expected to apply).
* No new `structure`/`class` (hypotheses stay raw binders — nothing for rule-2 models to pin).
  D1 N/A; D2 N/A (`ValuationSubring`-native; no spectral structure). **Not reconstruction**:
  Galois-action structure of given fields; no reach toward R1–R3.

## Axiom status

Standard axioms only expected on every declaration (`#print axioms` below re-runs on every
`lake build`). Ledger: `0 FOUNDATIONAL / 0 DEBT`, unchanged.
-/

open scoped Pointwise

namespace Anabelian

open ValuationSubring IsLocalRing

variable (K : Type*) {L : Type*} [Field K] [Field L] [Algebra K L] {A : ValuationSubring L}
  {A₀ : Subring ↥A}

/-- **The monogenicity engine** (Serre IV §1, the telescoping behind Prop. 5): if `σ` fixes the
subring `A₀` pointwise, then for every `x` in the subring generated by `A₀` and `π`, the
difference `σx − x` is divisible by `σπ − π`. Proved by `Subring.closure_induction`; the
multiplicative step is `σ(xy) − xy = σx·(σy − y) + (σx − x)·y`. -/
theorem smul_sub_dvd_of_mem_closure {σ : A.decompositionSubgroup K} {π : ↥A}
    (hfix : ∀ a ∈ A₀, σ • a = a) {x : ↥A}
    (hx : x ∈ Subring.closure ((A₀ : Set ↥A) ∪ {π})) :
    (σ • π - π) ∣ (σ • x - x) := by
  induction hx using Subring.closure_induction with
  | mem y hy =>
    rcases hy with hy | hy
    · rw [hfix y (SetLike.mem_coe.mp hy), sub_self]
      exact dvd_zero _
    · obtain rfl : y = π := Set.mem_singleton_iff.mp hy
      exact dvd_rfl
  | zero =>
    rw [smul_zero, sub_zero]
    exact dvd_zero _
  | one =>
    rw [smul_one, sub_self]
    exact dvd_zero _
  | add x y hx hy ihx ihy =>
    have h : σ • (x + y) - (x + y) = (σ • x - x) + (σ • y - y) := by
      rw [smul_add]; ring
    rw [h]
    exact dvd_add ihx ihy
  | neg x hx ihx =>
    have h : σ • (-x) - (-x) = -(σ • x - x) := by
      rw [smul_neg]; ring
    rw [h]
    exact dvd_neg.mpr ihx
  | mul x y hx hy ihx ihy =>
    have h : σ • (x * y) - x * y = σ • x * (σ • y - y) + (σ • x - x) * y := by
      rw [smul_mul']; ring
    rw [h]
    exact dvd_add (ihy.mul_left _) (ihx.mul_right _)

/-- **Detection on the uniformizer** (Serre, *Local Fields*, IV §1 Prop. 5, monogenic form):
if `A` is generated as a ring by an `σ`-fixed subring `A₀` together with `π`
(`Subring.closure (↑A₀ ∪ {π}) = ⊤`), then membership in the ramification filtration is detected
on `π` alone: `σπ − π ∈ 𝔪^(i+1) ⟹ σ ∈ G_i`. (The converse is the definition.) -/
theorem mem_ramificationGroup_of_smul_uniformizer_sub_mem {π : ↥A}
    (hgen : Subring.closure ((A₀ : Set ↥A) ∪ {π}) = ⊤)
    {σ : A.decompositionSubgroup K} (hfix : ∀ a ∈ A₀, σ • a = a)
    {i : ℕ} (hπ : σ • π - π ∈ maximalIdeal ↥A ^ (i + 1)) :
    σ ∈ ramificationGroup K A i := by
  rw [mem_ramificationGroup_iff]
  intro a
  have hx : a ∈ Subring.closure ((A₀ : Set ↥A) ∪ {π}) := by
    rw [hgen]; exact Subring.mem_top a
  obtain ⟨c, hc⟩ := smul_sub_dvd_of_mem_closure K hfix hx
  rw [hc]
  exact Ideal.mul_mem_right c _ hπ

/-- **The kernel of the tame character is exactly `G₁`** (as a subgroup of `G₀`), under the
monogenicity hypothesis. `⊇` is Pass 24's `tameCharacter_eq_one`. For `⊆`: `θ₀(σ) = 1` says
`u_σ ≡ 1 mod 𝔪`, so `σπ − π = π(u_σ − 1) ∈ 𝔪²`, and detection at `i = 1` puts `σ` in `G₁`. -/
theorem ker_tameCharacter (π : ↥A) (hspan : maximalIdeal ↥A = Ideal.span {π}) (hπ0 : π ≠ 0)
    (hgen : Subring.closure ((A₀ : Set ↥A) ∪ {π}) = ⊤)
    (hfix : ∀ σ : ↥(ramificationGroup K A 0), ∀ a ∈ A₀, σ.1 • a = a) :
    (tameCharacter K π hspan hπ0).ker
      = (ramificationGroup K A 1).subgroupOf (ramificationGroup K A 0) := by
  ext σ
  rw [MonoidHom.mem_ker, Subgroup.mem_subgroupOf]
  constructor
  · intro hσ
    -- Read `θ₀(σ) = 1` as: the residue of the tame unit is `1`.
    have h1 : Units.map (residue ↥A).toMonoidHom (tameUnit K π hspan σ.1) = 1 := hσ
    have hres : residue ↥A ↑(tameUnit K π hspan σ.1) = 1 := by
      have h2 := congrArg Units.val h1
      simpa using h2
    -- Hence `u_σ − 1 ∈ 𝔪 = (π)`.
    have hmem : (↑(tameUnit K π hspan σ.1) : ↥A) - 1 ∈ maximalIdeal ↥A := by
      have h3 : residue ↥A ↑(tameUnit K π hspan σ.1) = residue ↥A 1 := by
        rw [hres, map_one]
      exact (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).mp h3
    rw [hspan, Ideal.mem_span_singleton] at hmem
    obtain ⟨r, hr⟩ := hmem
    -- So `σπ − π = π(u_σ − 1) ∈ 𝔪²`, and detection at `i = 1` finishes.
    have hππ : σ.1 • π - π ∈ maximalIdeal ↥A ^ (1 + 1) := by
      rw [tameUnit_spec K π hspan σ.1, hspan, Ideal.span_singleton_pow,
        Ideal.mem_span_singleton]
      refine ⟨r, ?_⟩
      have h4 : π * ↑(tameUnit K π hspan σ.1) - π
          = π * ((↑(tameUnit K π hspan σ.1) : ↥A) - 1) := by ring
      rw [h4, hr]; ring
    exact mem_ramificationGroup_of_smul_uniformizer_sub_mem K hgen (hfix σ) hππ
  · intro hσ
    exact tameCharacter_eq_one K π hspan hπ0 σ hσ

/-- **Tame injectivity**: under the monogenicity hypothesis, the Pass-24 induced map
`G₀/G₁ →* 𝓀ˣ` is injective — the full classical level-0 embedding (Serre IV §2 Prop. 7 at
`i = 0`, conditional on monogenicity). -/
theorem tameQuotientHom_injective (π : ↥A) (hspan : maximalIdeal ↥A = Ideal.span {π})
    (hπ0 : π ≠ 0) (hgen : Subring.closure ((A₀ : Set ↥A) ∪ {π}) = ⊤)
    (hfix : ∀ σ : ↥(ramificationGroup K A 0), ∀ a ∈ A₀, σ.1 • a = a) :
    Function.Injective (tameQuotientHom K π hspan hπ0) := by
  rw [← MonoidHom.ker_eq_bot_iff]
  have h : (tameQuotientHom K π hspan hπ0).ker
      = Subgroup.map (QuotientGroup.mk' _) (tameCharacter K π hspan hπ0).ker :=
    QuotientGroup.ker_lift _ _ _
  rw [h, ker_tameCharacter K π hspan hπ0 hgen hfix, QuotientGroup.map_mk'_self]

/-- Corollary: the tame quotient `G₀/G₁` is **commutative** — it injects into the abelian `𝓀ˣ`.
(Stated as a bare `mul_comm` to avoid manufacturing a `CommGroup` instance from hypotheses.) -/
theorem tameQuotient_mul_comm (π : ↥A) (hspan : maximalIdeal ↥A = Ideal.span {π})
    (hπ0 : π ≠ 0) (hgen : Subring.closure ((A₀ : Set ↥A) ∪ {π}) = ⊤)
    (hfix : ∀ σ : ↥(ramificationGroup K A 0), ∀ a ∈ A₀, σ.1 • a = a)
    (x y : ↥(ramificationGroup K A 0) ⧸
      (ramificationGroup K A 1).subgroupOf (ramificationGroup K A 0)) :
    x * y = y * x :=
  tameQuotientHom_injective K π hspan hπ0 hgen hfix
    (by rw [map_mul, map_mul, mul_comm])

/-- Corollary: for **finite** `G₀`, the tame quotient `G₀/G₁` is **cyclic** — a finite group
embedding in the units of a domain (the residue field) is cyclic
(`isCyclic_of_injective_ringHom`). -/
theorem tameQuotient_isCyclic [Finite ↥(ramificationGroup K A 0)]
    (π : ↥A) (hspan : maximalIdeal ↥A = Ideal.span {π}) (hπ0 : π ≠ 0)
    (hgen : Subring.closure ((A₀ : Set ↥A) ∪ {π}) = ⊤)
    (hfix : ∀ σ : ↥(ramificationGroup K A 0), ∀ a ∈ A₀, σ.1 • a = a) :
    IsCyclic (↥(ramificationGroup K A 0) ⧸
      (ramificationGroup K A 1).subgroupOf (ramificationGroup K A 0)) :=
  isCyclic_of_injective_ringHom
    ((Units.coeHom (ResidueField ↥A)).comp (tameQuotientHom K π hspan hπ0))
    (Units.val_injective.comp (tameQuotientHom_injective K π hspan hπ0 hgen hfix))

-- Reproducible axiom audit (re-runs on every `lake build`). All standard-axioms-only.
#print axioms smul_sub_dvd_of_mem_closure
#print axioms mem_ramificationGroup_of_smul_uniformizer_sub_mem
#print axioms ker_tameCharacter
#print axioms tameQuotientHom_injective
#print axioms tameQuotient_mul_comm
#print axioms tameQuotient_isCyclic

end Anabelian
