/-
Copyright (c) 2026 Conor Mahany. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Conor Mahany
-/
import Anabelian.FiniteField
import Mathlib.NumberTheory.LocalField.Basic
import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.GroupTheory.QuotientGroup.Basic

/-!
# Rung L1, the inflection point: the unramified quotient of a local field

Passes 1–4 harvested the *easy/finite* L1 fruit. What remains in L1 — the **residue surjection**
`Gal(K̄/K) ↠ Gal(𝔽_q̄/𝔽_q)` (equivalently `Gal(K^ur/K) ≅ Gal(𝔽_q̄/𝔽_q)`), the prototype of the
local-to-residue map local reconstruction (R1) consumes — is **not** more low-hanging fruit. This
file confronts it, and the confrontation is this project's **first non-empty ledger entry**.

## The decision: (B) FOUNDATIONAL boundary, not (A) construction

The maximal-unramified Galois edifice is **entirely absent** from Mathlib (Pass-5 inventory: zero
hits for maximal-unramified extension / `K^ur` / residue Galois group / Frobenius lift). Mathlib has
only *ingredients* — `HenselianLocalRing` (+ `IsAdicComplete.henselianRing`),
`IsLocalRing.ResidueField.map` (residue functoriality), `Algebra.IsUnramified`. Crucially the
surjection's *content is* the unramified↔residue correspondence, so any `DEBT` axiom genuinely
*strictly below* it would either already be present (Hensel) or *be* the surjection (the cardinal
sin). So option (A) — scaffolding the construction with strictly-lower `DEBT` stubs — has no clean
move this pass; it is a genuine multi-pass construction.

We therefore take option **(B)**: the residue surjection is a **classical theorem** (Serre, *Local
Fields*, ch. I–II; Neukirch, *ANT*, ch. II) sitting **strictly below the R-targets** — R1 recovers
the local field *from* its abstract Galois group, whereas this is a structural fact *about* a given
local field's Galois group. We import it as a classified **`FOUNDATIONAL`** axiom
(`residueReduction_surjective`, logged in `AXIOM_LEDGER.md`, permitted `FOUNDATIONAL` for R1 per the
per-target list), and prove **real downstream structure** on it.

## What is proved (on the `FOUNDATIONAL` boundary)

* `Anabelian.unramifiedQuotient_iso` — *unlocked by the boundary*: the absolute Galois group `G_K`
  has a normal subgroup `N` (the kernel of the residue reduction; classically the inertia subgroup)
  with `G_K ⧸ N ≃* Field.absoluteGaloisGroup 𝓀[K]` (the residue Galois group), via the first
  isomorphism theorem. Rests on `residueReduction_surjective`.
* `Anabelian.residue_procyclic` — the residue Galois group is **procyclic** (its residue field
  `𝓀[K]` is finite), via Pass 2 (`frobenius_topologicalClosure_eq_top`). Standard axioms only.
* `Anabelian.unramifiedQuotient_procyclic` — the payoff combining both: **the unramified quotient of
  a local field's absolute Galois group is procyclic** (`G_K ⧸ N ≃* G_{𝓀[K]}`, topologically
  generated by a residue Frobenius). Rests on `residueReduction_surjective` + Pass 2.

## Honesty: what this is and is NOT

This is the honest sign the project reached its real work: the ledger is no longer empty. The
`FOUNDATIONAL` axiom posits the *existence* of a surjection `G_K ↠ G_{𝓀[K]}` — weaker than (and
implied by) the full classical theorem (which gives the *specific* continuous residue reduction with
kernel exactly the inertia subgroup). Tying `N` to Pass 4's `inertiaSubgroup` requires the valuation
on `K̄` (still absent) and is logged as remaining L1 work.

**Not reconstruction.** The residue surjection is a map between the Galois groups of *given* fields
(`K` and its residue field); nothing is recovered from an abstract topological group. No reach
toward R1–R3.

## Axiom status

`residue_procyclic` rests on standard axioms only. `unramifiedQuotient_iso` and
`unramifiedQuotient_procyclic` rest on the standard axioms **plus the `FOUNDATIONAL` entry
`Anabelian.residueReduction_surjective`** (see `AXIOM_LEDGER.md`). Pass-5 ledger delta:
**`FOUNDATIONAL` +1, `DEBT` +0**. Verified by the in-file `#print axioms` below.
-/

open scoped ValuativeRel

namespace Anabelian

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]

/-- **`FOUNDATIONAL` (classical; Serre, *Local Fields* I–II / Neukirch II).** The residue reduction
`Gal(K̄/K) ↠ Gal(𝓀̄/𝓀)` of a nonarchimedean local field is surjective: there is a surjective group
homomorphism from the absolute Galois group of `K` onto that of its residue field `𝓀[K]`.

Classified **`FOUNDATIONAL`** in `AXIOM_LEDGER.md`: it sits *strictly below* the R-targets (it is a
structural fact about a *given* local field's Galois group, not a reconstruction), and is permitted
as a `FOUNDATIONAL` input for R1 per the per-target list. This posits the *existence* of a
surjection — weaker than, and implied by, the full classical statement (specific continuous map,
kernel = inertia). The maximal-unramified construction that would *prove* it is absent from
Mathlib.

**Update (Pass 11): reclassified `FOUNDATIONAL → DEBT`.** The "construction absent" assessment was
corrected (`spectralNorm`-valuation on `K̄` and `IsKrasner` lifting are present), and the discharge
is now begun in `Anabelian/SpectralValuation.lean` (the spectral valuation ring `𝒪[K̄]` +
Galois-invariance, route step 1). This is now a `DEBT` we intend to discharge in-project, not an
external boundary; see `AXIOM_LEDGER.md` (Reclassification log + full route). -/
axiom residueReduction_surjective :
    ∃ φ : Field.absoluteGaloisGroup K →* Field.absoluteGaloisGroup 𝓀[K], Function.Surjective φ

/-- **Unlocked by the boundary.** The absolute Galois group of a local field `K` has a normal
subgroup `N` (the kernel of the residue reduction — classically the inertia subgroup) whose quotient
is isomorphic to the residue Galois group `Gal(𝓀̄/𝓀)`. Rests on `residueReduction_surjective`. -/
theorem unramifiedQuotient_iso :
    ∃ (N : Subgroup (Field.absoluteGaloisGroup K)) (_ : N.Normal),
      Nonempty ((Field.absoluteGaloisGroup K ⧸ N) ≃* Field.absoluteGaloisGroup 𝓀[K]) := by
  obtain ⟨φ, hφ⟩ := residueReduction_surjective K
  exact ⟨φ.ker, inferInstance, ⟨QuotientGroup.quotientKerEquivOfSurjective φ hφ⟩⟩

/-- The residue Galois group `Gal(𝓀̄/𝓀)` of a local field is **procyclic** (topologically generated
by a single element), because the residue field `𝓀[K]` is finite — Pass 2 applied to `𝓀[K]`. -/
theorem residue_procyclic :
    ∃ g : Field.absoluteGaloisGroup 𝓀[K], (Subgroup.zpowers g).topologicalClosure = ⊤ := by
  haveI : Fintype 𝓀[K] := Fintype.ofFinite _
  exact ⟨_, Anabelian.frobenius_topologicalClosure_eq_top 𝓀[K]⟩

/-- **The payoff.** The unramified quotient of a local field's absolute Galois group is procyclic:
`G_K` has a normal subgroup `N` with `G_K ⧸ N ≃* Gal(𝓀̄/𝓀)`, and that residue Galois group is
topologically generated by a single (Frobenius) element. Combines `residueReduction_surjective`
(`FOUNDATIONAL`) with Pass 2's procyclicity of finite-field absolute Galois groups. -/
theorem unramifiedQuotient_procyclic :
    ∃ (N : Subgroup (Field.absoluteGaloisGroup K)) (_ : N.Normal)
      (_ : (Field.absoluteGaloisGroup K ⧸ N) ≃* Field.absoluteGaloisGroup 𝓀[K]),
      ∃ g : Field.absoluteGaloisGroup 𝓀[K], (Subgroup.zpowers g).topologicalClosure = ⊤ := by
  obtain ⟨φ, hφ⟩ := residueReduction_surjective K
  haveI : Fintype 𝓀[K] := Fintype.ofFinite _
  exact ⟨φ.ker, inferInstance, QuotientGroup.quotientKerEquivOfSurjective φ hφ,
    _, Anabelian.frobenius_topologicalClosure_eq_top 𝓀[K]⟩

-- Reproducible axiom audit. `residue_procyclic`: standard only. The other two: standard +
-- the `FOUNDATIONAL` entry `Anabelian.residueReduction_surjective` (logged in `AXIOM_LEDGER.md`).
#print axioms unramifiedQuotient_iso
#print axioms residue_procyclic
#print axioms unramifiedQuotient_procyclic

end Anabelian
