/-
Copyright (c) 2026 Conor Mahany. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Conor Mahany
-/
import Anabelian.FiniteFieldZHat
import Mathlib.Topology.Algebra.Category.ProfiniteGrp.Limits
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Rung L1, toward `Gal(𝔽_q̄/𝔽_q) ≅ Ẑ`: the `Ẑ`-side inverse-system presentation

## The pass's job, and the honest outcome

Pass 6 built `zhatToGalois : Ẑ → Gal(K̄/K)` and proved it **surjective**; Pass 7 proved the
per-level data `Gal(𝔽_{q^n}/𝔽_q) ≅ ℤ/n`. The designated job of this pass was to **close the whole
iso** `Gal(𝔽_q̄/𝔽_q) ≅ Ẑ` axiom-free — bijectivity of `zhatToGalois`, packaged via
`Continuous.homeoOfEquivCompactToT2` + `MulEquiv.ofBijective`. Surjectivity is in hand; the missing
half is **injectivity**, equivalently the commuting square `Ẑ → ℤ/n ≅ Gal(𝔽_{q^n}/𝔽_q) ← Gal` at
every finite level.

**Closure is not reachable this pass, for a precise reason.** Every route to injectivity needs the
*Galois-side* level projection `Gal(K̄/K) → Gal(𝔽_{q^n}/𝔽_q)` — restriction to the degree-`n`
subextension. But Mathlib has **no `𝔽_{q^n}` as a `FiniteGaloisIntermediateField` of
`AlgebraicClosure K`** for finite fields: `GaloisField p n` exists only as a standalone splitting
field, not embedded in `K̄` with its restriction map. Constructing that subextension (and naming
its Galois group), then matching the *three* distinct index systems
(`FiniteIndexNormalSubgroup (Multiplicative ℤ)` for `Ẑ`, `OpenNormalSubgroup` for the generic limit,
`(FiniteGaloisIntermediateField)ᵒᵖ` for `Gal`) cofinally, is genuinely multi-pass. The numbered
sub-plan is in `ROADMAP.md`. We do **not** posit the iso or any piece (closing-by-positing is the
stacking trap, and a second `FOUNDATIONAL` is barred).

## What is proved — genuine, axiom-free `Ẑ`-side inverse-system machinery

We supply the `Ẑ`-side half of the injectivity square — the structural facts the cofinal matching
consumes — about the completion object `Ẑ` itself (not a finite-field corollary):

* `Anabelian.zhat_topologicalClosure_eq_top` — **`Ẑ` is procyclic**: the canonical generator
  `zhatGen = η(ofAdd 1)` topologically generates `Ẑ`. This is the `Ẑ`-side analogue of Pass 2's
  `frobenius_topologicalClosure_eq_top` for `Gal`; both `Ẑ` and `Gal(𝔽_q̄/𝔽_q)` are procyclic, and
  the remaining work is matching their finite cyclic quotient systems through `zhatToGalois`.
* `Anabelian.zhat_quotient_isCyclic` — **every finite (open-normal) quotient of `Ẑ` is cyclic**. So
  `Ẑ`'s inverse system (`ProfiniteGrp.toLimit_injective Ẑ` makes its projections point-separating)
  consists of finite **cyclic** groups — exactly matching `Gal`'s system of `ℤ/n`'s (Pass 7). This
  is the `Ẑ`-side inverse-system presentation the injectivity argument needs.

Both rest on the density of `η : Multiplicative ℤ → Ẑ` (`ProfiniteCompletion.denseRange`): `η`'s
image lands in the cyclic subgroup `zpowers zhatGen`, dense in the compact `Ẑ`; and any finite
discrete quotient of a group with a dense cyclic subgroup is cyclic.

## Honesty

This is **genuine but partial**: it closes the `Ẑ`-side structural input to injectivity, not the
iso. `Gal(𝔽_q̄/𝔽_q) ≅ Ẑ` is **NOT closed** here and is **NOT posited**; the remaining obstruction
(the Galois-side `𝔽_{q^n} ⊆ K̄` level projections + cofinal matching) is named and sub-planned in
`ROADMAP.md`. It is on-path (the `Ẑ`-side of the injectivity square), not an adjacent finite-level
lemma. **Recovers nothing from an abstract group**; no reach toward R1–R3. No load-bearing
hypothesis (both hold for `Ẑ` unconditionally), no new `structure`/`class`, hence no rule-2 or
owed-witness obligation.

## Axiom status

Standard axioms only (`#print axioms` below). Pass-8 ledger delta: **0 / 0** (no `DEBT`, no new
`FOUNDATIONAL`). The one existing `FOUNDATIONAL` entry (`residueReduction_surjective`, Pass 5) is
untouched and unused here.
-/

open CategoryTheory ProfiniteGrp ProfiniteGrp.ProfiniteCompletion

namespace Anabelian

/-- The canonical topological generator of `Ẑ`: the image of `1 ∈ ℤ` under the completion unit
`η : Multiplicative ℤ → Ẑ`. -/
noncomputable def zhatGen : ZHat :=
  etaFn (GrpCat.of (Multiplicative ℤ)) (Multiplicative.ofAdd (1 : ℤ))

/-- The image of `η : Multiplicative ℤ → Ẑ` lands in the cyclic subgroup generated by `zhatGen`
(because `Multiplicative ℤ` is generated by `ofAdd 1` and `η` is a homomorphism). -/
lemma etaFn_mem_zpowers_zhatGen (a : Multiplicative ℤ) :
    etaFn (GrpCat.of (Multiplicative ℤ)) a ∈ Subgroup.zpowers zhatGen := by
  obtain ⟨k, rfl⟩ : ∃ k : ℤ, Multiplicative.ofAdd k = a := ⟨Multiplicative.toAdd a, rfl⟩
  refine ⟨k, ?_⟩
  have hk : (Multiplicative.ofAdd (1 : ℤ)) ^ k = Multiplicative.ofAdd k := by
    rw [show Multiplicative.ofAdd k = Multiplicative.ofAdd (k • (1 : ℤ)) by
          rw [smul_eq_mul, mul_one], ofAdd_zsmul]
  change (eta (GrpCat.of (Multiplicative ℤ))).hom (Multiplicative.ofAdd (1 : ℤ)) ^ k
      = (eta (GrpCat.of (Multiplicative ℤ))).hom (Multiplicative.ofAdd k)
  exact (map_zpow _ _ _).symm.trans (congrArg _ hk)

/-- **`Ẑ` is procyclic.** The Frobenius-analogue generator `zhatGen = η(ofAdd 1)` topologically
generates `Ẑ`: the closure of `⟨zhatGen⟩` is the whole group. This is the `Ẑ`-side counterpart of
Pass 2's `frobenius_topologicalClosure_eq_top` for `Gal(𝔽_q̄/𝔽_q)`. -/
theorem zhat_topologicalClosure_eq_top :
    (Subgroup.zpowers zhatGen).topologicalClosure = ⊤ := by
  apply SetLike.coe_injective
  rw [Subgroup.topologicalClosure_coe, Subgroup.coe_top, ← dense_iff_closure_eq]
  exact (denseRange (GrpCat.of (Multiplicative ℤ))).mono
    (Set.range_subset_iff.mpr etaFn_mem_zpowers_zhatGen)

/-- A continuous map with dense range into a discrete space is surjective (its range is closed). -/
private lemma surj_of_denseRange_discrete {α X : Type*} [TopologicalSpace X] [DiscreteTopology X]
    {f : α → X} (h : DenseRange f) : Function.Surjective f := by
  rw [← Set.range_eq_univ]
  have hcl : IsClosed (Set.range f) := isClosed_discrete _
  rw [← hcl.closure_eq]; exact h.closure_range

/-- **Every finite quotient of `Ẑ` is cyclic.** For any open normal subgroup `U`, the finite
discrete quotient `Ẑ ⧸ U` is the image of the cyclic group `Multiplicative ℤ` under `η` then the
quotient map, whose range is dense hence (discrete codomain) all of `Ẑ ⧸ U`. Together with the
point-separating projections (`ProfiniteGrp.toLimit_injective`), this presents `Ẑ` as the inverse
limit of finite **cyclic** groups — matching `Gal(𝔽_q̄/𝔽_q)`'s system of `ℤ/n` (Pass 7). -/
theorem zhat_quotient_isCyclic (U : OpenNormalSubgroup ZHat) :
    IsCyclic (ZHat ⧸ U.toSubgroup) := by
  refine isCyclic_of_surjective
    ((QuotientGroup.mk' U.toSubgroup).comp (eta (GrpCat.of (Multiplicative ℤ))).hom) ?_
  rw [MonoidHom.coe_comp]
  exact surj_of_denseRange_discrete
    ((QuotientGroup.mk'_surjective _).denseRange.comp
      (denseRange (GrpCat.of (Multiplicative ℤ))) continuous_quotient_mk')

-- Reproducible axiom audit. Standard axioms only — no `DEBT`, no `FOUNDATIONAL` used.
#print axioms zhat_topologicalClosure_eq_top
#print axioms zhat_quotient_isCyclic

end Anabelian
