/-
Copyright (c) 2026 Conor Mahany. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Conor Mahany
-/
import Anabelian.Quotient.ComapIntegers
import Anabelian.Quotient.Basic
import Mathlib

/-!
# Toward Prop. 3 direction (ii): polynomial representation, and `L = K'(x)` (Pass 60)

Direction (ii) of Serre IV §1 Prop. 3 (`b ∣ a`) is the monic-division argument: write
`ι y = g(x)` for a polynomial `g` over `𝒪_K`, divide `g − y` by Serre's monic `F` in `B[X]`,
and kill the remainder by a degree count against `[L : K']`. This pass supplies the two
substrate facts that argument stands on:

* **the polynomial representation** (`exists_polynomial_map_eval_eq`, generic): membership in
  `Subring.closure (range f ∪ {x})` *is* being a polynomial value — every such element is
  `(P.map f).eval x`. At `𝒪_L` (`exists_polynomial_generator_rep`): with Pass 54's generator,
  every integer of `L` is `(g.map (extensionAlgebraMap K L)).eval x` for some `g` over
  `𝒪_K` — in particular `ι y` is.
* **`L = K'(x)`** (`adjoin_generator_eq_top`): the same generator generates `L` as a *field*
  over any intermediate `K'` — `IntermediateField.adjoin K' {x} = ⊤`. (Every integer is a
  polynomial in `x` over `𝒪_K ⊆ K'`; every element of `L` is an integer or the inverse of
  one — the valuation-subring dichotomy.) This is what will make `natDegree F = [L : K']`
  bite in the remainder-vanishing step: a nonzero polynomial over `K'` of degree
  `< [L : K'] = deg (minpoly K' x)` cannot kill `x`.
* **the commuting square** (`comapRingHom_comp_baseToComapRingHom`):
  `ι ∘ (𝒪_K → B) = extensionAlgebraMap K L` — the base map through `B` is the base map,
  needed to move `g`'s coefficients between the two routes.

## Honesty

Substrate for direction (ii) — **no reach toward R1–R3**; nothing recovered from an abstract
group. Neither the division nor the remainder-vanishing nor `b ∣ a` is claimed: this is the
representation and field-generation layer only. No new `structure`/`class`; no owed witness;
D1 N/A; D2 stays inside the Pass-29 proofs.

## Axiom status

Standard axioms only on every declaration (`#print axioms` below). Ledger: `0 FOUNDATIONAL /
0 DEBT`, unchanged.
-/

open ValuationSubring IsLocalRing Polynomial IntermediateField
open scoped Pointwise ValuativeRel
open ValuativeRel

namespace Anabelian

/-- **Closure membership is polynomial representation** (generic): every element of the
subring generated by `range f` and `x` is the value at `x` of a mapped polynomial. By
`Subring.closure_induction` — constants are `C`, the generator is `X`, and the ring
operations are the polynomial ring operations. -/
theorem exists_polynomial_map_eval_eq {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (x : S) {z : S}
    (hz : z ∈ Subring.closure ((f.range : Set S) ∪ {x})) :
    ∃ P : Polynomial R, (P.map f).eval x = z := by
  induction hz using Subring.closure_induction with
  | mem y hy =>
    rcases hy with hy | hy
    · obtain ⟨r, rfl⟩ := hy
      exact ⟨Polynomial.C r, by rw [Polynomial.map_C, Polynomial.eval_C]⟩
    · obtain rfl : y = x := Set.mem_singleton_iff.mp hy
      exact ⟨Polynomial.X, by rw [Polynomial.map_X, Polynomial.eval_X]⟩
  | zero => exact ⟨0, by simp⟩
  | one => exact ⟨1, by simp⟩
  | add a b _ _ iha ihb =>
    obtain ⟨P, hP⟩ := iha
    obtain ⟨Q, hQ⟩ := ihb
    exact ⟨P + Q, by rw [Polynomial.map_add, Polynomial.eval_add, hP, hQ]⟩
  | neg a _ iha =>
    obtain ⟨P, hP⟩ := iha
    exact ⟨-P, by rw [Polynomial.map_neg, Polynomial.eval_neg, hP]⟩
  | mul a b _ _ iha ihb =>
    obtain ⟨P, hP⟩ := iha
    obtain ⟨Q, hQ⟩ := ihb
    exact ⟨P * Q, by rw [Polynomial.map_mul, Polynomial.eval_mul, hP, hQ]⟩

section Tower

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]
variable (K' : Type*) [Field K'] [Algebra K K'] [FiniteDimensional K K']
variable {L : Type*} [Field L] [Algebra K' L] [Algebra K L] [IsScalarTower K K' L]
variable [FiniteDimensional K L]

/-- **The commuting square**: the base map `𝒪_K → B = 𝒪_L ∩ K'` followed by the tower
inclusion `ι : B → 𝒪_L` is Pass 29's base map `𝒪_K → 𝒪_L`. -/
theorem comapRingHom_comp_baseToComapRingHom :
    (comapRingHom K' (extensionIntegers K L)).comp (baseToComapRingHom K K' (L := L))
      = extensionAlgebraMap K L := by
  refine RingHom.ext fun c => ?_
  apply Subtype.ext
  change algebraMap K' L (algebraMap K K' (c : K)) = _
  rw [← IsScalarTower.algebraMap_apply K K' L, coe_extensionAlgebraMap]

end Tower

section Rep

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]
variable {L : Type*} [Field L] [Algebra K L] [FiniteDimensional K L]

/-- **Every integer of `L` is a polynomial in the generator**: with Pass 54's `x`, every
`z ∈ 𝒪_L` is `(g.map (extensionAlgebraMap K L)).eval x` for some `g` over `𝒪_K`. The
concrete `𝒪_L = 𝒪_K[x]`, element by element. -/
theorem exists_polynomial_generator_rep {x : ↥(extensionIntegers K L)}
    (hgen : Subring.closure
      (((extensionAlgebraMap K L).range : Set ↥(extensionIntegers K L)) ∪ {x}) = ⊤)
    (z : ↥(extensionIntegers K L)) :
    ∃ g : Polynomial ↥𝒪[K], (g.map (extensionAlgebraMap K L)).eval x = z := by
  refine exists_polynomial_map_eval_eq (extensionAlgebraMap K L) x ?_
  rw [hgen]
  exact Subring.mem_top z

end Rep

section Adjoin

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]
variable (K' : Type*) [Field K'] [Algebra K K']
variable {L : Type*} [Field L] [Algebra K' L] [Algebra K L] [IsScalarTower K K' L]
variable [FiniteDimensional K L]

/-- **`L = K'(x)`**: a ring generator of `𝒪_L` over `𝒪_K` generates `L` as a field over any
intermediate `K'` — `IntermediateField.adjoin K' {x} = ⊤`. Every integer lies in the adjoin
(closure induction: base elements are `K`-scalars, hence `K'`-scalars), and every element of
`L` is an integer or the inverse of one (the valuation-subring dichotomy
`mem_or_inv_mem`). The input to the degree count of direction (ii)'s remainder-vanishing. -/
theorem adjoin_generator_eq_top {x : ↥(extensionIntegers K L)}
    (hgen : Subring.closure
      (((extensionAlgebraMap K L).range : Set ↥(extensionIntegers K L)) ∪ {x}) = ⊤) :
    IntermediateField.adjoin K' {(x : L)} = ⊤ := by
  have hsub : ∀ z : ↥(extensionIntegers K L),
      (z : L) ∈ IntermediateField.adjoin K' {(x : L)} := by
    intro z
    have hz : z ∈ Subring.closure
        (((extensionAlgebraMap K L).range : Set ↥(extensionIntegers K L)) ∪ {x}) := by
      rw [hgen]; exact Subring.mem_top z
    induction hz using Subring.closure_induction with
    | mem y hy =>
      rcases hy with hy | hy
      · obtain ⟨c, rfl⟩ := hy
        have h1 : ((extensionAlgebraMap K L c : ↥(extensionIntegers K L)) : L)
            = algebraMap K L (c : K) := coe_extensionAlgebraMap K L c
        rw [h1, IsScalarTower.algebraMap_apply K K' L]
        exact (IntermediateField.adjoin K' {(x : L)}).algebraMap_mem _
      · obtain rfl : y = x := Set.mem_singleton_iff.mp hy
        exact IntermediateField.subset_adjoin K' _ (Set.mem_singleton _)
    | zero => simp
    | one => simp
    | add a b _ _ iha ihb => simpa using add_mem iha ihb
    | neg a _ iha => simpa using neg_mem iha
    | mul a b _ _ iha ihb => simpa using mul_mem iha ihb
  rw [_root_.eq_top_iff]
  intro l _
  rcases (extensionIntegers K L).mem_or_inv_mem l with hl | hl
  · exact hsub ⟨l, hl⟩
  · have h2 := hsub ⟨l⁻¹, hl⟩
    have h3 : l = (l⁻¹)⁻¹ := (inv_inv l).symm
    rw [h3]
    exact inv_mem h2

end Adjoin

-- Reproducible axiom audit (re-runs on every `lake build`). All standard-axioms-only.
#print axioms exists_polynomial_map_eval_eq
#print axioms comapRingHom_comp_baseToComapRingHom
#print axioms exists_polynomial_generator_rep
#print axioms adjoin_generator_eq_top

end Anabelian
