/-
Copyright (c) 2026 Conor Mahany. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Conor Mahany
-/
import Anabelian.ClassField.MaximalAbelian
import Mathlib

/-!
# L3.1 (first brick): the Herbrand quotient (Pass 87)

The cyclic layer of the Neukirch-route class field theory (the Pass-85 design) opens with
its central bookkeeping device. For a commutative group `M` and a pair of endomorphisms
`f, g : M →* M` with `f ∘ g = g ∘ f = 1` (the "periodic complex" condition — for a cyclic
Galois action: `f = N` the norm, `g = σ/1` the twisted difference):

* **`herbrandH f g`** — the cohomology carrier `ker f / im g` (for the cyclic action:
  `Ĥ⁰ = H²`; swapped: `Ĥ¹ = H¹`, matching Mathlib's
  `Rep.FiniteCyclicGroup.groupCohomologyIsoEven/Odd` — that bridge is a later brick);
* **`herbrandQuotient f g : ℚ`** — `q(M) = |Ĥ⁰|/|Ĥ¹|`;
* **`herbrandQuotient_eq_one_of_finite`** — the TRIVIALITY THEOREM: finite `M` has
  `q(M) = 1`, by the double counting `|ker f|·|im f| = |M| = |ker g|·|im g|` (the P74
  Lagrange/first-isomorphism idiom, reused verbatim).

NOT in Mathlib (verified by search this pass). The remaining L3.1 bricks:
multiplicativity of `q` in short exact sequences (needs the six-term calculus or a direct
snake-style count), the `Rep`-bridge identifying `herbrandH` with Mathlib's `Hⁱ` for
cyclic groups, and the concrete `q(Lˣ) = [L:K]`-type computations (via Hilbert 90 and the
unit filtration) that feed the class-formation axioms.

## Honesty

Abstract group-theoretic bookkeeping — **no reach toward R1–R3**, and not yet any class
field theory: the reciprocity map (L3.3) is far. Rule-2 note: `herbrandH` is a plain
`def` (a quotient of proved objects), not a `structure`/`class`; the pair hypotheses
(`f ∘ g = 1`, `g ∘ f = 1`) are load-bearing in the classical theory but here appear only
as hypotheses of theorems that visibly use them (`range_le_ker` — dropping them makes
`herbrandH` still well-formed but the counting false; no counterexample owed since no
sharpness is claimed). No owed witness; D1 N/A; D2 untouched.

## Axiom status

Standard axioms only (`#print axioms` below). Ledger: `0 FOUNDATIONAL / 0 DEBT`, unchanged.
-/

namespace Anabelian


variable {M : Type*} [CommGroup M] (f g : M →* M)

/-- When `f ∘ g = 1`, the range of `g` lands in the kernel of `f` — the complex
condition. -/
theorem range_le_ker (hfg : ∀ x, f (g x) = 1) : g.range ≤ f.ker := by
  rintro _ ⟨x, rfl⟩
  exact hfg x

/-- The cohomology carrier of the pair at `f`: `ker f / im g`. For a finite cyclic group
generated by `σ` acting on `M`, with `f = N` (the norm/trace) and `g = σ - 1`
(multiplicatively: `x ↦ σ(x)·x⁻¹`), this is `Ĥ⁰ = H²`; swapping gives `Ĥ¹ = H¹` — the
two periodic cohomologies of Mathlib's `Rep.FiniteCyclicGroup.groupCohomologyIsoEven/Odd`
(the bridge to that framework is a later L3.1 brick). -/
def herbrandH : Type _ :=
  f.ker ⧸ (g.range.subgroupOf f.ker)

noncomputable instance : Group (herbrandH f g) :=
  inferInstanceAs (Group (f.ker ⧸ (g.range.subgroupOf f.ker)))

/-- **The Herbrand quotient** of the pair: `q(M) = |ker f / im g| / |ker g / im f|`
(Serre VIII §4, Neukirch IV §7 — the two-endomorphism form, which is the
formalization-friendly one). `ℚ`-valued; `Nat.card = 0` on infinite carriers makes the
convention harmless (the theorems assume the finiteness they need). -/
noncomputable def herbrandQuotient : ℚ :=
  (Nat.card (herbrandH f g) : ℚ) / (Nat.card (herbrandH g f) : ℚ)

/-- Lagrange inside the kernel: `|ker f| = |ker f / im g| · |im g|`. -/
theorem card_ker_eq_card_herbrandH_mul (hfg : ∀ x, f (g x) = 1) :
    Nat.card f.ker = Nat.card (herbrandH f g) * Nat.card g.range := by
  have h1 := Subgroup.card_eq_card_quotient_mul_card_subgroup (g.range.subgroupOf f.ker)
  rw [h1]
  congr 1
  exact Nat.card_congr
    (Subgroup.subgroupOfEquivOfLe (range_le_ker f g hfg)).toEquiv

/-- The first-isomorphism counting: `|M| = |ker f| · |im f|`. -/
theorem card_eq_card_ker_mul_card_range :
    Nat.card M = Nat.card f.ker * Nat.card f.range := by
  have h1 := Subgroup.card_eq_card_quotient_mul_card_subgroup f.ker
  rw [h1, Nat.card_congr (QuotientGroup.quotientKerEquivRange f).toEquiv]
  ring

/-- **THE TRIVIALITY THEOREM** (Serre VIII §4 Prop. 8, Neukirch IV 7.4): a FINITE module
has Herbrand quotient `1` — the counting `|ker f|·|im f| = |M| = |ker g|·|im g|` cancels
everything. The workhorse: in the exact-sequence calculus it kills finite error terms, so
`q` only sees the "infinite part" of a module (e.g. `q(𝒪_L) = q(U_L)`-style reductions in
the unit-cohomology computations ahead). -/
theorem herbrandQuotient_eq_one_of_finite [Finite M]
    (hfg : ∀ x, f (g x) = 1) (hgf : ∀ x, g (f x) = 1) :
    herbrandQuotient f g = 1 := by
  have hfin1 : Finite f.ker := inferInstance
  have hfin2 : Finite (herbrandH f g) :=
    inferInstanceAs (Finite (f.ker ⧸ (g.range.subgroupOf f.ker)))
  have hfin3 : Finite (herbrandH g f) :=
    inferInstanceAs (Finite (g.ker ⧸ (f.range.subgroupOf g.ker)))
  have h1 := card_ker_eq_card_herbrandH_mul f g hfg
  have h2 := card_ker_eq_card_herbrandH_mul g f hgf
  have h3 := card_eq_card_ker_mul_card_range (M := M) f
  have h4 := card_eq_card_ker_mul_card_range (M := M) g
  -- |herbH f g| · |range g| · |range f| = |M| = |herbH g f| · |range f| · |range g|
  have h5 : Nat.card (herbrandH f g) * Nat.card g.range * Nat.card f.range
      = Nat.card (herbrandH g f) * Nat.card f.range * Nat.card g.range := by
    rw [← h1, ← h3, ← h2, ← h4]
  have hpos1 : 0 < Nat.card (herbrandH g f) := Nat.card_pos
  have hpos2 : 0 < Nat.card f.range := Nat.card_pos
  have hpos3 : 0 < Nat.card g.range := Nat.card_pos
  have h6 : Nat.card (herbrandH f g) = Nat.card (herbrandH g f) := by
    have h7 : Nat.card (herbrandH f g) * (Nat.card g.range * Nat.card f.range)
        = Nat.card (herbrandH g f) * (Nat.card g.range * Nat.card f.range) := by
      ring_nf
      ring_nf at h5
      exact h5
    exact Nat.eq_of_mul_eq_mul_right (Nat.mul_pos hpos3 hpos2) h7
  rw [herbrandQuotient, h6]
  have hpos4 : 0 < Nat.card (herbrandH g f) := Nat.card_pos
  rw [div_self]
  exact_mod_cast hpos4.ne'


-- Reproducible axiom audit (re-runs on every `lake build`). Standard-axioms-only.
#print axioms range_le_ker
#print axioms herbrandH
#print axioms herbrandQuotient
#print axioms card_ker_eq_card_herbrandH_mul
#print axioms card_eq_card_ker_mul_card_range
#print axioms herbrandQuotient_eq_one_of_finite

end Anabelian
